print('*************************************************')
print('\t         PROGRAM PYTHON')
print('\tOLEH  : QIRANA SITI MAULIDA HAKIM')
print('\tKELAS : X PPLG 1')
print('*************************************************')
